name: Price Scraper

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '17 0 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run price scraper
      run: python get_dynamic_price.py

    - name: Commit and push updated price_data.csv
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"
        git add price_data.csv
        git commit -m "Update price_data.csv" || echo "No changes to commit"
        git push
